[package]
name = "lmux-server"
version.workspace = true
edition.workspace = true

[dependencies]
lmux-core = { path = "../lmux-core" }
lmux-term = { path = "../lmux-term" }
lmux-store = { path = "../lmux-store" }
tokio.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde_json.workspace = true
ulid.workspace = true
tracing.workspace = true
base64.workspace = true
bytes = "1"
fs2.workspace = true

[dev-dependencies]
tempfile.workspace = true
